FoodDiaryApp/Models/ErrorViewModel.cs
namespace FoodDiaryApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FoodDiaryApp/Models/FoodDiaryEntryViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FoodDiaryApp.Models
{
    public class FoodDiaryEntryViewModel
    {
        public int Id { get; set; }
        [Required]
        public DateTime Date { get; set; }

        [Required]
        public string MealType { get; set; }

        [Required]
        public string Description { get; set; }

        public string Symptoms { get; set; } = string.Empty;

        public string Analysis { get; set; } = string.Empty;
    }
}

FoodDiaryApp/Models/UserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace FoodDiaryApp.Models
{
    public class UserViewModel
    {
        public string UserName { get; set; }

        public string Password { get; set; }
    }
}

FoodDiaryApp/Controllers/FoodDiaryController.cs
using Entities;
using FoodDiaryApp.Models;
using FoodDiaryApp.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FoodDiaryApp.Controllers
{
    public class FoodDiaryController : Controller
    {
        private readonly CalorieEstimatorService _calorieEstimator;
        private readonly AiNutritionService _aiNutritionService;
        private readonly ApplicationDbContext _context;

        public FoodDiaryController(ApplicationDbContext context, CalorieEstimatorService calorieEstimatorService, AiNutritionService aiNutritionService)
        {
            _context = context;
            _calorieEstimator = calorieEstimatorService;
            _aiNutritionService = aiNutritionService;
        }

        public IActionResult Index()
        {
            var userId = HttpContext.Session.GetInt32("UserId");

            if (!userId.HasValue)
            {
                return RedirectToAction("Login", "Users");
            }

            var entries = _context.FoodDiaryEntries
                .Where(e => e.UserId == userId)
                .Select(e => new FoodDiaryEntryViewModel
                {
                    Id = e.Id,
                    Date = e.Date,
                    MealType = e.MealType,
                    Description = e.Description,
                    Symptoms = e.Symptoms,
                    Analysis = e.Analysis
                })
                .ToList();

            return View(entries);
        }

        [HttpGet]
        public IActionResult CreateEntry()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateEntry([FromBody] FoodDiaryEntryViewModel entry)
        {
            if (ModelState.IsValid)
            {
                var userId = HttpContext.Session.GetInt32("UserId");
                if (userId == null)
                {
                    return RedirectToAction("Login", "Users");
                }

                var analysisResult = await _aiNutritionService.GetCaloriesForFoodItemAsync(entry.Description);
                //var isConnected = await _calorieEstimator.TestConnection();
                //var calorieEstimate = await _calorieEstimator.EstimateCalories(entry.Description);

                var newEntry = new FoodDiaryEntry
                {
                    UserId = userId.Value,
                    Date = entry.Date,
                    MealType = entry.MealType,
                    Description = entry.Description,
                    Symptoms = entry.Symptoms,
                    Analysis = analysisResult
                };

                _context.FoodDiaryEntries.Add(newEntry);
                await _context.SaveChangesAsync();

                return Json(new { Success = true });
            }

            return Json(new { Success = false });
        }

        [HttpGet]
        public IActionResult GetSelectedEntry(int id)
        {
            var entry = _context.FoodDiaryEntries
                .Where(e => e.Id == id)
                .Select(e => new FoodDiaryEntryViewModel
                {
                    Id = e.Id,
                    Date = e.Date,
                    MealType = e.MealType,
                    Description = e.Description,
                    Symptoms = e.Symptoms,
                    Analysis = e.Analysis
                })
                .FirstOrDefault();

            return Json(entry);
        }
    }
}

FoodDiaryApp/Controllers/HomeController.cs
using FoodDiaryApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FoodDiaryApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FoodDiaryApp/Controllers/UsersController.cs
using Entities;
using FoodDiaryApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace FoodDiaryApp.Controllers
{
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public UsersController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register([FromBody] UserViewModel user)
        {
            if (ModelState.IsValid)
            {
                var hashedPassword = BCrypt.Net.BCrypt.HashPassword(user.Password);

                var newUser = new User
                {
                    Username = user.UserName,
                    Password = hashedPassword
                };

                _context.Users.Add(newUser);
                await _context.SaveChangesAsync();
                return RedirectToAction("Login");
            }
            return View(user);
        }

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login([FromBody] UserViewModel user)
        {
            var loginUser = _context.Users
                .FirstOrDefault(u => u.Username == user.UserName);

            if (loginUser != null && BCrypt.Net.BCrypt.Verify(user.Password, loginUser.Password))
            {
                HttpContext.Session.SetInt32("UserId", loginUser.Id);
                return Json(new { Success = true });
            }

            
            return Json(new { Success = false });
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear(); 
            return RedirectToAction("Login");
        }
    }
}

FoodDiaryApp/Views/FoodDiary/CreateEntry.cshtml
@model FoodDiaryApp.Models.FoodDiaryEntryViewModel

<div ng-controller="FoodDiaryController">
    <h2 class="text-background">Create Diary Entry</h2>
    <form ng-submit="createEntry()">
        <div class="form-group">
            <label class="text-background">Date</label>
            <input type="date" class="form-control" ng-model="entry.Date" required />
        </div>
        <div class="form-group">
            <label class="text-background">Meal Type</label>
            <input type="text" class="form-control" ng-model="entry.MealType" required />
        </div>
        <div class="form-group">
            <label class="text-background">Description</label>
            <textarea class="form-control" ng-model="entry.Description" required></textarea>
        </div>
        <div class="form-group">
            <label class="text-background">Symptoms</label>
            <textarea class="form-control" ng-model="entry.Symptoms"></textarea>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Create Entry</button>
    </form>
</div>

FoodDiaryApp/Views/FoodDiary/Index.cshtml
@model IEnumerable<FoodDiaryApp.Models.FoodDiaryEntryViewModel>

<div class="entryListView" ng-controller="FoodDiaryController">
    <div class="card-container">
        @foreach (var entry in Model)
        {
            <div class="card" ng-click="editFoodDiary(@entry.Id)">
                <div class="header">
                    <div class="title">@entry.MealType - @entry.Date.ToString("yyyy-MM-dd")</div>
                </div>
                <div class="content">
                    <p><b>Description</b> @entry.Description</p>
                    <p><b>Symptoms</b> @entry.Symptoms</p>
                    <p><b>Analysis</b> @entry.Analysis</p>
                </div>
            </div>

        }

    </div>

    <div id="editModal" class="modal">
        <div class="modal-content">
            <span class="close" ng-click="closeModal()">&times;</span>
            <h3 style="color:black;">Edit Record {{ selectedRecord.date | date:'yyyy-MM-dd' }}</h3>
            <form ng-submit="saveRecord()">
                <label for="mealType">Meal Type:</label>
                <input type="text" id="mealType" ng-model="selectedRecord.mealType" required>

                <label for="description">Description:</label>
                <input type="text" id="description" ng-model="selectedRecord.description" required>

                <label for="symptoms">Symptoms:</label>
                <input type="text" id="symptoms" ng-model="selectedRecord.symptoms">

                <label for="analysis">Analysis:</label>
                <input type="text" id="analysis" ng-model="selectedRecord.analysis">

                <input type="submit" value="Save">
            </form>
        </div>
    </div>
</div>

FoodDiaryApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center text-background">
    <h1 class="display-4">Welcome</h1>
    <p>
        When completing the food and symptom diary, it is important to provide precise information. Please include details such as quantity, brand, type, and the amount consumed. For
        instance, when documenting bread consumption, kindly specify "2 slices of multigrain bread."
    </p>
</div>

FoodDiaryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" ng-app="FoodDiaryApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoodDiaryApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FoodDiaryApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FoodDiaryApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        @if (Context.Session.GetInt32("UserId") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FoodDiary" asp-action="Index">Records</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="FoodDiary" asp-action="CreateEntry">Add Record</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container footerArea">
            <p>
                &copy; 2024 - FoodDiaryApp - Designed by Alex 
            </p>
            
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.8.2/angular.min.js"></script>
    <script src="~/Scripts/app.js"></script>
</body>
</html>

FoodDiaryApp/Views/Users/Login.cshtml
@model FoodDiaryApp.Models.UserViewModel

<div class="container" ng-controller="UsersController">
    <h2 class="text-background">Login</h2>
    <form ng-submit="login()">
        <div class="form-group">
            <label for="username" class="text-background">Username</label>
            <input type="text" id="username" class="form-control" ng-model="user.Username" required />
        </div>
        <div class="form-group">
            <label for="password" class="text-background">Password</label>
            <input type="password" id="password" class="form-control" ng-model="user.Password" required />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Login</button>
    </form>
</div>

FoodDiaryApp/Views/Users/Register.cshtml
@model FoodDiaryApp.Models.UserViewModel

<div class="container" ng-controller="UsersController">
    <h2 class="text-background">Register</h2>
    <form ng-submit="register()">
        <div class="form-group">
            <label for="username" class="text-background">Username</label>
            <input type="text" id="username" class="form-control" ng-model="user.UserName" required />
        </div>
        <div class="form-group">
            <label for="password" class="text-background">Password</label>
            <input type="password" id="password" class="form-control" ng-model="user.Password" required />
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>